config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, only: [:index, :show, :new, :edit, :update] do
    resources :requests, only: [:new, :create]
  end
  resources :requests, only: [:index, :update, :edit, :destroy, :show] do
    resources :reviews, only: [:new, :show, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :professional, class_name: "User", foreign_key: "professional_id", optional: true
  # when request is destroyed, destroy will be called on its associated reviews.
  has_many :reviews, dependent: :destroy
  has_many_attached :photos
  enum status: [:Creada, :Cotizada, :Aceptada, :Pagada], _default: "Creada"
  validates :title, presence: true
  validates :detail, presence: true
  validates :city, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  validates :request_id, uniqueness: { scope: :user_id, message: "Ya hiciste una reseña" }
  belongs_to :request
  belongs_to :user
  has_many_attached :photos
  validates :content, presence: true
  validates :rating, numericality: true, inclusion: { in: (1..5) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
  has_many :requests
  has_one_attached :photo
  has_many_attached :photos
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true
  validates :city, presence: true
  validates :role, presence: true
  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # # Uncomment when you *really understand* Pundit!
  # # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # # def user_not_authorized
  # #   flash[:alert] = "You are not authorized to perform this action."
  # #   redirect_to(root_path)
  # # end
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :city, :phone_number, :role, :photo, :job])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :city, :phone_number, :role, :photo, :job])
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @users = User.where(role: "profesional")
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_user, only: %i[new]

  def show
    @request = Request.find(params[:id])
    authorize @request
  end

  def index
    @request = policy_scope(Request).where(user: current_user)
    # @review_search = Review.find(params[:request_id])
    # @review_all = Review.all
    @request_by = Request.all
    @review_by = Review.all
    @review = Review.new

    if current_user.role == "profesional"
      @my_requests = Request.where(professional_id: current_user.id)
      @requests = Request.where(user_id: current_user.id)
    else
      @requests = Request.where(user_id: current_user.id)
    end
  end

  def new
    @request = Request.new
    authorize @request
  end

  def create
    @request = Request.new(request_params)
    @request.user_id = current_user.id
    authorize @request
    if @request.save
      redirect_to requests_path
    else
      render :new
    end
  end

  def edit
    @request = Request.find(params[:id])
    authorize @request
  end

  def update
    @request = Request.find(params[:id])
    @request.update(request_params)
    authorize @request
    redirect_to requests_path(@request)
  end

  def destroy
    @request = Request.find(params[:id])
    @request.destroy
    authorize @request
    redirect_to requests_path(@request)
  end

  # def change_status
  #   if @request.price.empty?
  #     @request.status == "Creada"
  #   else
  #     @request.status ==
  #   end
  # end

  private

  def request_params
    params.require(:request).permit(:title, :city, :detail, :professional_id, :price, :comment, :status, photos: [])
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # before_action

  def show
    @request = Request.find(params[:request_id])
    @review = Review.find(params[:id])
    authorize @review
  end

  def new
    @request = Request.find(params[:request_id])
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @request = Request.find(params[:request_id])
    @review.user = current_user
    authorize @review
    @review.request = @request
    if @review.save
      redirect_to requests_path
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating, photos:[])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @users = policy_scope(User)
    if params[:query].present?
    @users = User.where("job ILIKE ? AND role = 'profesional'", "%#{params[:query]}%").or(User.where("city ILIKE ? AND role = 'profesional'", "%#{params[:query]}%"))
    else
      @users = User.where(role: "profesional")
    end

    @markers = @users.geocoded.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude,
        info_window: render_to_string(partial: "info_window", locals: { user: user })
      }
    end
  end

  def show
    # Mostrar las reviews del profesional
    @user = User.find(params[:id])
    @my_requests = Request.where(professional_id: @user)
    authorize @user
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    @user.update(user_params)
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :phone_number, :city, :role, :photo, :job, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Servicios Ya! La manera más simple de contratar un servicio.</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/82cb13e596.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <script src="https://kit.fontawesome.com/82cb13e596.js" crossorigin="anonymous"></script>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
      AOS.init();
    </script>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner"
  style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://img.freepik.com/free-photo/empty-red-brick-wall_53876-31790.jpg?w=996);">
    <h1 class="text-center">Servicios Ya!</h1>
    <p class="text-center">La manera más simple de contratar un servicio</p>
    <div class="search">
        <%= form_tag users_path, method: :get, class: "form-search" do %>
        <%= text_field_tag :query,
            params[:query],
      class: "form-control",
            placeholder: "Buscar por servicio o ubicación"%>
             <%= button_tag(type: "submit", class: "btn btn-default", id: "btn-search") do %>
            <i class="fas fa-search"></i> Buscar
        <% end %>
      <% end%>
    </div>
  </div>
  <div class="container-fluid">
    <div class="sombreadora">
    <div id="carouselExampleIndicators" class="carousel carousel-dark slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active" >
        <h2 class= "text-center"> Encontralo </h2>
          <p class= "text-center">¿Necesitas un especialista? Busca por rubro o ubicación. <br> Envía una solicitud explicando tu problema. </p>
        </div>
        <div class="carousel-item">
        <h2 class= "text-center"> Agendalo </h2>
          <p class= "text-center"> Coordina con el profesional los detalles, espera la cotización. <br> ¿Estás de acuerdo? Acuerdan el día y horario. </p>
        </div>
        <div class="carousel-item w-100">
        <h2 class= "text-center"> ¡Listo! </h2>
          <p class= "text-center"> Realizá el pago online de manera segura, resguardamos tu dinero. <br> Recibís tu solución y le pagamos a nuestro especialista.  </p>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
      </div>
    </div>
      <div class="profesionales-destacados">
        <p class= "text-center">Profesionales destacados <%= @count_requests %> </p>
      </div>
    <div class="card-users">
      <% 3.times do %>
        <% number_rand = rand(0...@users.size)%>
         <div class="users-index">
                <div class="picture">
                  <% if @users[number_rand].photo.attached? %>
                    <%= cl_image_tag @users[number_rand].photo.key %>
                  <% else %>
                    <%= image_tag "profilepic.png" %>
                  <% end %>
                </div>
          <div class="users-content">
              <h5 class="name"><%= @users[number_rand].first_name %></h5>
              <h6 class="title"><%=@users[number_rand].job%></h6>
              <h6 class="location"><%= @users[number_rand].city %></h6>
              <p class="fa fa-star" aria-hidden="true"> </p>
              <p class="fa fa-star" aria-hidden="true"> </p>
              <p class="fa fa-star" aria-hidden="true"> </p>
              <p class="fa fa-star" aria-hidden="true"> </p>
              <p class="fa fa-star" aria-hidden="true"> </p>
          </div>
          <ul class="icons">
            <li><%= link_to user_path(@users[number_rand].id) do %> <i class="fa fa-info-circle"></i> <% end %></li>
            <li><%= link_to new_user_request_path(@users[number_rand].id) do %><i class="fa fa-envelope"></i><% end %></li>
          </ul>
        </div>
      <% end %>
  </div>
  <div class="link-ver">
    <%= link_to 'Ver todos profesionales', users_path , class: 'btn btn-default' %>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/requests/_comentarios.html.erb
<div class="container">
  <% @review_by.each do |review| %>
      <div class="cards">
        <div class="card card-1" id="card-m">
            <div class="card_title">
              <h3 class="name">
                <%="#{User.find(review.user_id).first_name}" %>
              </h3>
            </div>
            <p class="card__stars">
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
            </p>
            <p class="card__content">
              <%= review.content %>
            </p>
        </div>
      </div>
  <% end %>
</div>

app/views/requests/_form.html.erb
<div>
  <%= simple_form_for [@user, @request] do |f| %>
    <%= f.input :title, label: "Título" %>
    <%= f.input :city, label: "Dirección" %>
    <%= f.input :detail, label: "Descripción" %>
    <%= f.input :photos, label: "Fotos", as: :file, input_html: { multiple: true } %>
    <%= f.input :professional_id, as: :hidden, input_html: { value: "#{@user.id}"} %>
    <%= f.submit "Guardar", class: "btn btn-default" %>
  <% end %>
</div>

app/views/requests/_pagos.html.erb
<h2> Tus pagos</h2>
<p> $5.000 </p

app/views/requests/_solicitudes.html.erb
    <%# request.photos.each do |photo| %>
      <%#= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
    <%# end%>

<div class="container">
  <div class="cards">
    <% requests.each do |request| %>
      <div class="card-request">
        <img src="https://res.cloudinary.com/mpdlo/image/upload/v1646918763/production/Recurso_1_g0t3ok.png" />
        <div class="card-request-infos">
          <h2><%= "#{request.title}"%></h2>
          <p> <%= "Dirección: #{request.city}" %> </p>
          <p> <%= "Detalles: #{request.detail}" %> </p>
          <%# <button class="btn-grad">Ver Detalles <span> </span>&rarr;</button>
          <div class="link-ver"> %>
          <%= link_to 'Ver más detalles', request_path(request), class: 'btn btn-request' %>
        </div>
      </div>
    <% end%>
  </div>
</div>

app/views/requests/_trabajos.html.erb
<div class="container">
  <div class="cards">
  <div class="row">
    <% my_requests.each do |request| %>
    <div class="col-md-12 mt-3">
      <div class="card-request center-card">
        <img src="https://res.cloudinary.com/mpdlo/image/upload/v1646918763/production/Recurso_1_g0t3ok.png" />
        <div class="card-request-infos">
          <h2><%= link_to request.title, request_path(request.id) %></h2>
          <p> <%= "Dirección: #{request.city}" %> </p>
          <p> <%= "Detalles: #{request.detail}" %> </p>
          <p> <%= "Precio $ #{request.price}" %> </p>
          <% request.photos.each do |photo| %>
            <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
          <% end%>
        </div>
      </div>
    </div>
    <% end%>
  </div>
  </div>
</div>

app/views/requests/edit.html.erb
<div class="container col-6 mt-5">
  <% if current_user.id == @request.professional_id %>
    <br>
      <div class="titulo row justify-content-center">
        <h3 class="text-center">Editar Solicitud</h3>
      </div>
    <div>
      <%= simple_form_for [@user, @request] do |f| %>
        <%= f.input :title, :disabled => true %>
        <%= f.input :city, :disabled => true %>
        <%= f.input :detail, :disabled => true %>
        <%= f.input :photos, :disabled => true %>
        <%= f.input :price, placeholder: "Cotización" %>
        <%= f.input :comment, placeholder: "Comentario" %>
        <%= f.submit "Guardar", class: "btn-default" %>
      <% end %>
    </div>
  <% else %>
        <br>
      <div class="titulo row justify-content-center">
        <h3 class="text-center">Editar Solicitud</h3>
      </div>
      <div>
        <%= simple_form_for [@user, @request] do |f| %>
          <%= f.input :title, label: "Servicio" %>
          <%= f.input :city, label: "Dirección" %>
          <%= f.input :detail, label: "Descripción" %>
          <%= f.input :photos, label: "Fotos", as: :file, input_html: { multiple: true } %>
          <%= f.input :price, :disabled => true %>
          <%= f.input :comment, placeholder: "Comentario", :disabled => true %>
          <%= f.submit "Guardar", id: "volver", class: "btn btn-default" %>
          <%= link_to 'Cancelar solicitud', request_path(@request), id:"cancel-show", class: 'btn btn-default' , method: :delete, data: {confirm: "Estás seguro de borrar?"} %>
          <%= link_to 'Volver', requests_path , class: 'btn btn-default' %>
        <% end %>
      </div>
     <%end%>
  <%# <%= link_to 'Volver a búsquedas', users_path, id: "volver", class: 'btn btn-default mt-2' %>
</div>

app/views/requests/new.html.erb
<div class="container col-6 mt-5">
  <h1> Nueva Solicitud - <%= "#{@user.first_name}"%></h1>
  <p> <%= "#{@user.job}"%> </p>
  <%= render 'form', user: @user, request: @request %>
</div>

app/views/requests/show.html.erb
<div class="container abc col-6 mt-5" id= "container-tablero" >
  <div class="show-request">
    <div class="show-request-infos">
      <h1><%= @request.title %></h1>
      <div class="detalles">
        <ul class="sinpuntos">
          <li>Detalles: <%= @request.detail %></li>
          <li>Dirección: <%= @request.city %></li>
          <li>Comentarios del profesional: <%= @request.comment %></li>
          <li>Precio: <%= @request.price %></li>
          <li><% @request.photos.each do |photo| %>
                <%= cl_image_tag photo.key, height: 200, width: 300, crop: :fill %>
                <% end %></li>
        </ul>
      </div>
        <% if @request.professional_id != current_user.id %>
          <% if @request.reviews.empty? %>
          <br>
          <%= link_to 'Hacer una reseña', new_request_review_path(@request.id) , class: 'btn btn-default' %>
          <% else %>
            <h3>Tu reseña</h3>
            <p> Comentario: <%= @request.reviews.first.content %> </p>
            <p> Rating: <%= @request.reviews.first.rating %> </p>
          <% end %>
        <% end %>
      <%= link_to 'Editar solicitud', edit_request_path(@request.id) , class: 'btn btn-default' %>
      <%= link_to 'Volver', requests_path , class: 'btn btn-default' %>
    </div>
  </div>
</div>

app/views/review/new.html.erb
<div class="container col-6">
  <h1> Nueva review: </h1>

  <%= render 'form_review', review: @review, request: @request %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/mpdlo/image/upload/v1646918763/production/Recurso_1_g0t3ok.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Inicio", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Tablero", requests_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.photo.key %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "profilepic.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mi perfil", edit_user_path(current_user), class: "dropdown-item" %>
              <%#= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li><%= link_to "Inicio", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Iniciar sesión", new_user_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div id= "search-index" class="search-users">
    <%= form_tag users_path, method: :get do %>
    <i class="fas fa-search" style="position: absolute; z-index: 10; margin-left: 305px; margin-top:12px; color:white;"></i>
    <%= submit_tag "  Buscar", style:"position: absolute; margin-left: 299px;", class: "btn btn-default", id: "btn-search" %>
    <%= text_field_tag :query,
      params[:query], class: "form-control", placeholder: "Buscar por servicio o ubicación"%>
    <% end%>
</div>

<div class="container index">
  <div class="container d-flex">
    <div class="row">
      <div class="col-12 col-sm-6 col-md-4 col-lg-3">
        <% if @users.blank? %>
          <p> No se encuentra el profesional </p>
        <% end %>
        <br>
        <% @users.each do |user| %>
          <% if user_signed_in? == false || user.id != current_user.id %>
            <div data-aos="fade-right">
              <div class="users-index">
                <div class="picture">
                  <% if user.photo.attached? %>
                    <%= cl_image_tag user.photo.key %>
                  <% else %>
                    <%= image_tag "profilepic.png" %>
                  <% end %>
                </div>
                <div class="users-content">
                  <p id="star" class="fa fa-star" aria-hidden="true"> </p>
                  <p id="star" class="fa fa-star" aria-hidden="true"> </p>
                  <p id="star" class="fa fa-star" aria-hidden="true"> </p>
                  <p id="star" class="fa fa-star" aria-hidden="true"> </p>
                  <h3 class="name"><%= "#{user.first_name} #{user.last_name}" %></h3>
                  <h4 class="job"><%= user.job %></h4>
                  <h4 class="city"><%= user.city %></h4>
                </div>
                <ul class="icons">
                  <li><%= link_to user_path(user.id) do %><i class="fa fa-info-circle"></i><% end %></li>
                  <li><%= link_to new_user_request_path(user.id) do %><i class="fa fa-envelope"></i><% end %></li>
                </ul>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="container map-container">
      <div class="map" style="width: 100%; height: 100vh; margin-top:20px;"
        data-controller="mapbox"
        data-mapbox-markers-value="<%= @markers.to_json %>"
        data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/users/show.html.erb
<div class= "container-fluid" id="container-show">
  <div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
      <div class="col-md-4">
        <%#= cl_image_tag @user.photo.key %>
        <%# <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png"
          class="img-fluid rounded-start" alt="..."> %>
      </div>
      <div class="col-md-8" id="card-body-user">
        <div class="card-body">
          <h3 class="card-title"><%= @user.first_name %></h3>
          <p class="card-text">
            <li> Servicios: <%= @user.job %>
            <li> Ciudad: <%= @user.city %> </li>
            <li> Telefono: <%= @user.phone_number %> </li>
            <p class="fa fa-star" aria-hidden="true" style= "color:	#EABE3F"> </p>
            <p class="fa fa-star" aria-hidden="true" style= "color:	#EABE3F"> </p>
            <p class="fa fa-star" aria-hidden="true" style= "color:	#EABE3F"> </p>
            <p class="fa fa-star" aria-hidden="true" style= "color:	#EABE3F"> </p>
            <p class="fa fa-star" aria-hidden="true" style= "color:	#EABE3F"> </p>
          </p>
        </div>
      </div>
    </div>
  </div>
  <h2 class="text-center mt-5">Reseñas</h2>
  <div class="card border-light mb-3" style="max-width: 40rem;" id="card-show">
    <div class="card-body">
      <div class="card_title"> <h3 class= "text-center"></h3> </div>
        <%# <p class="card-text"><% @my_requests.each do |request| %>
          <% if @my_requests.nil? || @my_requests.first.reviews.nil? %>
           <%= "No tiene reseñas" %>
          <% else %>
            <ul  class= "text-center">
              <li><%= @my_requests.first.reviews.first.content %> Rating: <%= @my_requests.first.reviews.first.rating %>
               <p class="card__stars" >
                <p class="fa fa-star" class= "text-center" id="estrellas" aria-hidden="true" style= "color:	#EABE3F"> </p>
                <p class="fa fa-star" id="estrellas" aria-hidden="true" style= "color:	#EABE3F"> </p>
                <p class="fa fa-star" id="estrellas" aria-hidden="true" style= "color:	#EABE3F"> </p>
                <p class="fa fa-star" id="estrellas" aria-hidden="true" style= "color:	#EABE3F"> </p>
                <p class="fa fa-star" id="estrellas" aria-hidden="true" style= "color:	#EABE3F"> </p>
               </p>
            </ul>
          <% end %>
        <%# <% end %></p>
      </div>

</div>
<div class="btns-show">
  <% if user_signed_in? == false %>
      <%= link_to 'Crear solicitud', new_user_request_path(@user.id), class: 'btn btn-default' %>
   <% elsif @user.id != current_user.id %>
        <%= link_to 'Crear solicitud', new_user_request_path(@user.id), class: 'btn btn-default' %>
    <% else %>
  <% end %>
  <%= link_to 'Volver a búsquedas', users_path, class: 'btn btn-default' %>
<div>